baseURL = "https://sh0e1.com"
languageCode = "ja"
title = "sh0e1.com"
theme = "anatole"
googleAnalytics = "UA-131592660-1"

[params]
  title = "sh0e1.com"
  author = "sh0e1"
  description = "Software Engineer / Go / PHP / JavaScript / GCP Professional Cloud Architect"
  profilePicture = "images/profile.png"
  mainSections = ["post"]
  customCss = ["css/custom.css"]
  images = ["images/profile.png"]

  ## Math settings
  [params.math]
    enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

  # Social links
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/sh0e1"

  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/sh0e12uatanal3e"

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
