baseURL = "https://sh0e1.com/"
languageCode = "ja"
title = "sh0e1.com"
theme = "m10c"
googleAnalytics = "UA-131592660-1"

[params]
  author = "sh0e1"
  description = "Software Engineer / Go / PHP / JavaScript / GCP Professional Cloud Architect"
  avatar = "/avatar.png"

  [[params.social]]
    name = "github"
    url = "https://github.com/sh0e1"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/sh0e12uatanal3e"

  #[params.style]
  #  darkestColor = "#f8f9fb"
  #  darkColor = "#ffffff"
  #  primaryColor = "#303d4e"
  #  lightColor = "#4b5766"
  #  lightestColor = "#3eaf7c"
